"""initial schema

Revision ID: b86339102b96
Revises: 
Create Date: 2026-08-21 11:34:51.507401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86339102b96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('machine_type', sa.Enum('MILLING', 'TURBOFAN', name='machinetype'), nullable=False),
    sa.Column('quality_type', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.Enum('WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('kind', sa.Enum('FAILURE_PROBABILITY', 'ANOMALY_SCORE', 'RUL', name='alertkind'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_ts'), 'alerts', ['ts'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('technician', sa.String(length=120), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_ts'), 'sensor_readings', ['ts'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('rul_cycles', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('NORMAL', 'WARNING', 'CRITICAL', name='healthstatus'), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['sensor_readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_ts'), 'predictions', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_ts'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_sensor_readings_ts'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_alerts_ts'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('machines')
    # ### end Alembic commands ###
